version: '3.4'

services:
  tarefa-app:
    build:
      context: ./tarefa-app
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - tarefa-api
  tarefa-api:
    image: ${DOCKER_REGISTRY-}tarefa-api
    container_name: tarefa-api
    build:
      context: ./tarefa-api
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "5000:80"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80 
  
  database:
    image: mysql
    container_name: mysqldb
    ports:
      - "3307:3306"
    expose:
      - "3306"
    volumes:
      - dbmysql-volume:/var/lib/mysql
    restart: always
    environment:
        MYSQL_RANDOM_ROOT_PASSWORD: 1
        MYSQL_USER: admin
        MYSQL_PASSWORD: mv
        MYSQL_DATABASE: tarefasdb

volumes:
  dbmysql-volume:
