version: '3.4'

services:
  tarefaapi:
    image: ${DOCKER_REGISTRY-}tarefaapi
    container_name: tarefa.api
    build:
      context: .
      dockerfile: Tarefas.API/Dockerfile
    depends_on:
    - database
    ports:
    - "5000:8080"
    restart: always
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
  
  database:
    image: mysql
    container_name: mysqldb
    ports:
    - "3307:3306"
    expose:
    - "3306"
    volumes:
    - dbmysql-volume:/var/lib/mysql
    restart: always
    environment:
        MYSQL_RANDOM_ROOT_PASSWORD: 1
        MYSQL_USER: admin
        MYSQL_PASSWORD: mv
        MYSQL_DATABASE: tarefasdb

volumes:
  dbmysql-volume:
